### ISSUE TITLE
List of Bugs on my marketplace.

### ISSUE THREAD

**Issue by abid-rafiq** [Arcadier/Plug-In-support#19]
I am still trying to contact you guys, but the response time is too slow. My marketplace is going to launch soon, and it has multiple bugs from the dev side. Below are the bugs with their respective videos to reproduce.

-- Onclick of category the page is too slow, it takes 9 seconds to load.
https://drive.google.com/file/d/1V-S8sxd2TGqUgcxq_fUScoH4w0sNkUSI/view

-- When searched any item it takes too long to load.
https://drive.google.com/file/d/1ID24fQyGpj-F1ix29DledxazTNsEuW_G/view

-- Price filter on items list is not working, probably in the current theme.
https://drive.google.com/file/d/19IdaI_D_ESWUrFJpu0bJtn1IKWTE3qt0/view

-- When purchasing an order the timezone is not being displayed in a user's purchased time
https://drive.google.com/file/d/1b25XMtMFj8IXyYl9pcdE-o7cDUDHAbC0/view

-- Buyer Account couldn't receive any welcome email, nor in mail logs.
https://drive.google.com/file/d/1i4WvJED6MYJhaUnKvkbwtec_Z5S9c1FV/view

-- Possibility to Decline Pre-Approved Payment after unsuccessful payment.
https://drive.google.com/file/d/1LlzBUx5y8qI3lHNF7dhmfYBXr20Hk7ny/view

Please respond as soon as possible it's taking too many business days.

**Comment by ArcadierPteLtd** [comment]
-- Load speed issues have been addressed 
-- Price filter issue has been addressed
-- Timezone issue: Currently all EDMs Arcadier sends out are only in UTC timestamp due to the database; you might want to use the email template editor to add a notification in the email content to let users know about the timezone of the timestamp
-- Welcome mail issue has been addressed
