### ISSUE TITLE
Found some Dead Links on theme

### ISSUE THREAD

**Issue by abid-rafiq** [Arcadier/Plug-In-support#25]
I was optimizing my current website https://www.hitchplanner.com. I found some dead links which need to be resolved to optimize its way better. It looks like some of the URLs are not working on the theme.

The deadlink utility is here:
[https://www.deadlinkchecker.com/website-dead-link-checker.asp](https://www.deadlinkchecker.com/website-dead-link-checker.asp )

![image](https://user-images.githubusercontent.com/43639053/89331736-b012df80-d6ab-11ea-9386-973624d42f07.png)

**Comment by rachaelchin** [comment]
Hi abid-rafiq,

For the dead links, they are due to various reasons: 

1. For some links, we only accept POST. So when the system checked that if it is using GET and the response will be 404. 
2. For the FAQ, we noticed that you are not using our default FAQ but used the pages tool to create one.
3. For Instagram, this is not part of our default functionality thus we cannot comment about this
4. For the images, we have informed our front-end team about it and they will be updating the CSS. So, do stay tuned for updates. 

Thanks and regards,
Rachael from the product marketing team
