### ISSUE TITLE
Delivery Methods didn't display on the checkout Page

### ISSUE THREAD

**Issue by NoteworthySandbox** [Arcadier/Plug-In-support#37]
Hi

Need help regarding delivery methods on the checkout page. Only pick-up address is listed in delivery methods. Please see the images. 

My marketplace is 
https://noteworthy.sandbox.arcadier.io/
![Screen Shot 2022-01-04 at 12 30 11 AM](https://user-images.githubusercontent.com/94594965/147972208-e964e472-82a5-4e16-b62a-c4ffaa6f147c.png)
![Screen Shot 2022-01-04 at 12 30 35 AM](https://user-images.githubusercontent.com/94594965/147972216-de16393c-518b-49d4-9eee-a56aaa9362c3.png)

**Comment by Arcadier-Support** [comment]
Hi,

Apologies for the late reply. The reason why the delivery methods are not showing is because the item you are checking out with has no weight indicated in the "weight" field (refer to screenshot below). 
![Screenshot 2022-01-06 at 6 13 09 PM](https://user-images.githubusercontent.com/67083361/148367596-7932fab0-0730-45f9-a3c7-5044271c462f.png)

This field can be found under edit items on the merchant portal. Since the delivery methods is configuring via weight, the weight field needs to be added for the delivery method to calculate the delivery fee. Please find below the actual result of our test once we added the weight field for the same product. 

![Screenshot 2022-01-06 at 6 16 14 PM](https://user-images.githubusercontent.com/67083361/148367396-0491cedd-c810-4b7b-8f9a-6a7fa51c17c3.png)

**Comment by NoteworthySandbox** [comment]
Hi,

Thank you For your reply. If you mentioned this into your documentation that will be great
